sources:
  - name: nba
    description: "Source data from the NBA"
    database: MASTER
    schema: STAGE
    tables:
      - name: nba_stats
        description: "Player stats data from the NBA"
      - name: salaries
        description: "NBA players salaries"