nba_stats:
  outputs:
    dev:
      account: WBSVXOX-WD11131
      database: MASTER
      password: TableDeskDesk1!
      role: ACCOUNTADMIN
      schema: STAGE
      threads: 10
      type: snowflake
      user: MZUBAC1235
      warehouse: COMPUTE_WH
  target: dev
